arch:
  input_feed: "esrt.input_feed.LSEInputFeed"
  learning_algorithm: "esrt.models.LSE"
  dataset_type: "esrt.dataset.LSEDataset"
data:
  data_dir: "/home/share/yinxiangkun/transformed/digital_music/seq_min_count5/"
  input_train_dir: "/home/share/yinxiangkun/transformed/digital_music/seq_min_count5/seq_query_split/"
  model_dir: "/home/share/yinxiangkun/saved/lse_embed+0_digital_music/"
  logging_dir: "/home/share/yinxiangkun/log/lse_embed+0_digital_music/"

experiment:
  subsampling_rate: 0.0001
  max_train_epoch: 20
  steps_per_checkpoint: 200
  seconds_per_checkpoint: 3600
  decode: false
  test_mode: "product_scores"
  rank_cutoff: 100

hparams:
  window_size: 5
  embed_size: 100
  max_gradient_norm: 5.0
  init_learning_rate: 0.5
  L2_lambda: 0.005
  query_weight: 0.5
  negative_sample: 5
  net_struct: "LSE"
  similarity_func: "bias_product"
  batch_size: 384
