arch:
  input_feed: "esrt.input_feed.ZAMInputFeed"
  learning_algorithm: "esrt.models.ZAM"
  dataset_type: "esrt.dataset.ZAMDataset"
data:
  data_dir: "/home/share/yinxiangkun/transformed/electronics/seq_min_count5/"
  input_train_dir: "/home/share/yinxiangkun/transformed/electronics/seq_min_count5/seq_query_split/"
  model_dir: "/home/share/yinxiangkun/saved/zam_embed+0_electronics/"
  logging_dir: "/home/share/yinxiangkun/log/zam_embed+0_electronics/"

experiment:
  subsampling_rate: 0.0001
  max_train_epoch: 20
  steps_per_checkpoint: 200
  seconds_per_checkpoint: 3600
  decode: false
  test_mode: "product_scores"
  rank_cutoff: 100

hparams:
  window_size: 5
  embed_size: 300
  max_gradient_norm: 5.0
  init_learning_rate: 0.5
  L2_lambda: 0.005
  query_weight: 0.5
  negative_sample: 5
  net_struct: "simplified_fs"
  similarity_func: "bias_product"
  user_struct: "asin_zero_attention"
  num_heads: 5
  attention_func: 'default'
  max_history_length: 10
  batch_size: 384
